name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build --no-cache . --file Dockerfile --tag ifreecomm/fluent-bit:latest
        docker login -u kangliqi -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker push ifreecomm/fluent-bit:latest
      
